version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: python -m unittest tests/*.py
          name: Unittests

workflows:
  main:
    jobs:
      - build-and-test
